import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bleep, BleepWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

if System.get_env("BLEEP_SECURE_SERVER") do
  host = System.get_env("PHX_HOST") || "example.com"

  config :bleep, BleepWeb.Endpoint,
    force_ssl: [host: host, hsts: true, rewrite_on: [:x_forwarded_proto]]
end

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Bleep.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
