bpm = 120

content = {

markdown [[
# A Techno Music Programming Masterclass With The Black Dog
## Atmosphere and structure
]],

markdown [[
A simple techno structure has an intro, a middle section and an outro.  You could start with some synth sounds.
]],

editor [[
push_fx("stereo_delay",{feedback=0.7,wetLevel=0.4})
for i = 1, 16 do
  sample("tbd_highkey_c4",{
     level=0.4,
     duration=4,
     rate=0.5})
  sleep(2)
  sample("tbd_highkey_c4",{
     level=0.4,
     duration=4,
     rate=0.75})
  sleep(14)
end
]],

markdown [[
Then the drums come in.
]],

editor [[
for bars = 1, 16 do
  drum_pattern("B--B --h- B--- B-h-", {
     duration=0.25, 
     level=0.2,
     B="bd_sone",
     h="tbd_perc_tap_1"})
end
]],

markdown [[
Create tension with layers of atmospheric samples. Use random numbers generated by **randf** to introduce variation. For example here we set the sample rate randomly between 0.1 and 1.5.
]],

editor [[
for i = 1, 4 do
  sample("burst_reverb", {
      rate=randf(0.1, 1.5),
      level=randf(0.1, 0.3),
      cutoff=randf(800, 5000)})
  sleep(4)
end
]],

markdown [[
Layer more tracks to create the middle section, then take one away at a time to create the outro.
]],

editor [[
for i = 1, 8 do
  sample("tbd_fxbed_loop", {level=0.1,duration=1.6})
  sleep(8)
end
]],

markdown [[
### Expert tips from The Black Dog
]],

markdown [[
We often control synth parameters over a long period to gradually build up tension.
]],

editor [[
cut = 300
for i = 1, 16 do
  sample("tbd_fxbed_loop", {
     level=0.1, 
     cutoff=cut,
     duration=1.6})
  cut = cut * 1.2
  sleep(4)
end
]],

}